### ISSUE TITLE
Special rules upgrades don't add to the unit profile.

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#10]
If you add an upgrade granting a special rule, it should update the unit's Special Rules section. Similar to how if you upgrade to something like "Wizard(2)" it updates the unit profile.

![image](https://user-images.githubusercontent.com/8975633/134237748-bbb42fbd-4e95-47ba-956d-993f037b0462.png)

**Comment by AdamLay** [comment]
This is fixed, but Karaz might want to comment on the UI...
