### ISSUE TITLE
Roaster view : List mode

### ISSUE THREAD

**Issue by BaptisteD** [AdamLay/opr-army-forge#104]
Make the list full width on mobile, limited to 480px on desktop. 

Add 16px margin between the units and the spells.

![Screenshot_20211020-130505](https://user-images.githubusercontent.com/2566847/138086437-02449ba9-c0e0-48e0-ac43-dfaf4aa865f5.jpeg)

**Comment by AdamLay** [comment]
Closing as this view was removed... we'll pick up the new tabular "List View" soon!
