### ISSUE TITLE
Upgrade section categories / grouping

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#110]
onepageanon — Today at 9:50 PM
like, I opened the pathfinders to give them sniper rifles
but I'm first hit by a full page of options 
-----
maybe change the upgrade text
to something like "Sergeant: Upgrade with one:"
and then I can pull out the first half of the text and use that

**Comment by Darguth** [comment]
@AdamLay @BaptisteD I think the A1 upgrade list is *always* leader-based upgrades. Both for heroes and unit leaders. I wonder if we just brainstorm ways to treat that specific upgrade list differently? I'm pretty sure that will cover 90% or more of the use cases where the behavior OPA is describing would be present.

**Comment by BaptisteD** [comment]
Sorry, I'm a bit lost with this issue and I'm not sure to understand the problem. Would you have a screenshot or something to illustrate it ?

**Comment by AdamLay** [comment]
We have added some re-ordering to help with those. Closing until we have a more specific requirement raised.
