### ISSUE TITLE
UX Feedback

### ISSUE THREAD

**Issue by RobMayer** [AdamLay/opr-army-forge#117]
(copied from Discord at request of Adam):

On the desktop version:
- I'm not sold on the three-column layout. I think you'd be better served by having a two-column layout (left column is the army list, right column is your list) and have a modal for adding and viewing a unit. without a unit selected the empty right column is just a waste of space.
- Clicking on a unit in My list lets me edit it (duh, makes sense), but it feels like left clicking a unit in the army list should do something - the cursor changes to a pointer, and i kinda of expected to be able to see a detail view or somethin'. The net effect of this is that I have to add a unit to my list to see what options are available for it - I can't read it and then choose to add it.
- on the army list column there seems to be groupings of units, but no hint as to why the groupings exist.
- I like the functionality of the Full/Compact toggle, but it's mystery-meat. I didn't understand what it did until I clicked it.
- On the top menu bar, you've got plenty of room to show more than just an icon for the options (the warning sign and the eyeball) - might as well use it to spell out what the icons mean.
- Love the card layout, but you might want to look at Masonry layouts rather than relying on Grid (proper Masonry support is coming soon™️ to css, but there are non-pure css ways to make it work)
- when I'm in the "list builder mode" the button to go to "View list mode" is on the right. Once there, the button to return is an X and is on the left. When I go back to the army-builder mode, the left-most button is a left-pointing arrow that goes back to "create a new army". Just inconsistent navigation iconography and placement.

Going over to mobile:
- the two-page layout still doesn't work - I feel like you've got enough space to do the same 2-column layout with a modal as above.

**Comment by AdamLay** [comment]
Oops - an old one! I think most of this has been addressed now, thanks!
