### ISSUE TITLE
"Recent lists" under "Open A List"

### ISSUE THREAD

**Issue by RobMayer** [AdamLay/opr-army-forge#118]
This idea presumes you can and do keep multiple lists in LocalStorage rather than just the currently auto-saving one.

how about a list of recently created or recently edited lists that is currently in local storage, including the "autosaved" list.

**Comment by Darguth** [comment]
@BaptisteD I'm 50/50 on the usefulness of this. It can save a single tap, but I also think it can add clutter and distraction to the screen. So I'll leave it to you if we should pursue it or close it as not planning to implement.

**Comment by RobMayer** [comment]
FWIW, Now that I grok how the front page works? I'm inclined to withdraw the idea. I hadn't, at the time, realized that the Open a List would show a recent list - I thought it was a Open-from-file upload button. The splash is better off being this pithy, imho.
