### ISSUE TITLE
"Upgrade any model with" upgrade type is single-select rather than # of models

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#12]
Ex. AOF Dwarves v2.11 army book upgrade list K1 for Steam-Power Suits. They should be able to take a rifle per model, but UI only allows a single selection checkbox.

![image](https://user-images.githubusercontent.com/8975633/134241380-a4982a2f-9c1c-4f7c-bf5a-590d2149ad89.png)

**Comment by AdamLay** [comment]
@Darguth can you please re-test this and close if you think the logic is working now, thanks.
