### ISSUE TITLE
Combine units that are the exact same in Card View (and add count to title)

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#129]

**Comment by Darguth** [comment]
@AdamLay @BaptisteD Do we actually want this? Recalling our 3 print/view use cases:
1. Match-side use on phone or tablet
2. Print army list
3. Print army cards

I think we only want this in maybe use-case #2? In #1 we're considering game aide functionality like activation markers and damage tracking that this would interfere. In use case #3 I'm not sure what value this provides.

**Comment by AdamLay** [comment]
At the moment for me the obvious(?) answer is to add a "Combine similar units" option to the display settings? For me I have wanted this in both 1. and 2. which is why I added it - best to leave it up to the user?

**Comment by Darguth** [comment]
@AdamLay Fair enough. We can always revisit if and when we make any changes to the screen where the context breaks. Works-as-intended from what I'm seeing so going to close and move to Done.
