### ISSUE TITLE
Identical options in different upgrade lists not working

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#13]
This is a rather unique case I think, but looking at AOF Dwarves v2.11 upgrade lists J1 and N1 each allow you to upgrade one model with Shrapnel Bombs. This displays properly as two lists with a checkbox in Army Forge, but the problem is that if you click on either checkbox it selects both. So you can only get 1 upgrade, whereas rules-as-written I believe you could take 2.

![image](https://user-images.githubusercontent.com/8975633/134242204-b3767acd-8cad-4ee0-a350-e6fb2db026c3.png)

**Comment by AdamLay** [comment]
This is no longer an issue after migrating to WC format data
