### ISSUE TITLE
Fix iOS

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#132]
iOS doesn't seem to like the regular expressions containing lookbehind/negative lookbehind.

Perhaps find a way of re-writing these? it's stopping the entire application from working.

**Comment by HENNIROCKS** [comment]
Confirming this for Safari on both mobile and desktop platforms; iPad OS 15.1/ 4th gen. iPad Pro, macOS 11.6/ 2018 MacBook Pro.

Console error `SyntaxError: Invalid regular expression: invalid group specifier name`.
