### ISSUE TITLE
Battle Brothers 2.50 Master Brother bike upgrade missing

### ISSUE THREAD

**Issue by ScornMandark** [AdamLay/opr-army-forge#133]
In the Battle Brothers 2.50 army list, the Master Brother is able to upgrade to a jetpack, combat bike, or destroyer armor (upgrade options B).  In the builder, the combat bike option is missing.

Army List
![Screenshot_20211029-130108_Drive](https://user-images.githubusercontent.com/7913700/139474919-040f2873-6ad4-4da9-9f42-76a56ebf9525.jpg)

Builder
![Screenshot_20211029-130129_Chrome](https://user-images.githubusercontent.com/7913700/139474899-b4b622b6-0897-40ca-adb7-cc44463204d8.jpg)

**Comment by Darguth** [comment]
This is very likely a source data issue, so I've moved it to the WC backlog: https://github.com/schnick3rs/opr-web-companion/issues/56
