### ISSUE TITLE
Orc Marauders - Goblin Tank cannot select upgrades

### ISSUE THREAD

**Issue by metalman42** [AdamLay/opr-army-forge#134]
After adding Goblin Tank to an Orc Marauders army list, I cannot choose upgrades. They appear as a list with radio buttons, but do not highlight when moused over and don't do anything when clicked. Tried removing and re-adding the unit and starting a new army in a different browser but no change.

**Comment by Darguth** [comment]
This is a source data issue so I've migrated it to the WC backlog. https://github.com/schnick3rs/opr-web-companion/issues/55
