### ISSUE TITLE
Robot Legions - Sniper "Hunter" upgrade cost bug

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#135]
The Robot Legion Sniper unit has the upgrade "Hyperspace Reapers (Hunter)" which costs 460 points, see image below

![image](https://user-images.githubusercontent.com/93403931/139487990-9746b0c2-ed98-4904-8d26-0bf4c702de21.png)

Cost is a bug that breaks the system confirmed by OPA 

![image](https://user-images.githubusercontent.com/93403931/139488297-44a9edea-9691-41c8-b012-00a82ee89207.png)
(see OPR Discord > #Army-Forge > onepageanon (time 29/10/2021 6:30pm GMT) for the original transcript).

**Comment by AdamLay** [comment]
Looks as though this is resolved - costs 20pt now.
