### ISSUE TITLE
Robot Legions - Fortress of destruction optional upgrade incorrectly giving psychic(5)

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#136]
The Robot Legions Fortress of destruction has an optional upgrade (-145 points) to replace the "Destruction Pulse" with the "Nanobot Wraith-Shard (Psychic(3))". Fortress is already Psychic(2) and upgrades to Psychic(5) (should be Psychic(3) as far as i'm aware)

This may be due to the fact that the "Nanobot Wraith-Shard" is classed as Equipment, idk, not an experienced coder, see image below

![image](https://user-images.githubusercontent.com/93403931/139488875-8883f9c1-de1e-4bbb-93bf-5d7c55681434.png)

**Comment by IGlautier** [comment]
This might be to do with how total psychic values are calculated for display. I think it just iterates over all items that give psychic rule and sums their rank value

**Comment by AdamLay** [comment]
Psychic is now an exception to the rule and takes the max value available rather than summing all:
```
        const rating = key === "Psychic"
          // Take Highest
          ? Math.max(...group.map(rule => parseInt(rule.rating)))
          // Sum all occurrences
          : group.reduce((total, next) => next.rating ? total + parseInt(next.rating) : total, 0);
```
