### ISSUE TITLE
Upgrading Orc Mob with Carbines does not give them CCWs.

### ISSUE THREAD

**Issue by KnTenshi** [AdamLay/opr-army-forge#142]
Description:
Upgrading Orc Mob with Carbines does not give them CCWs.

Steps to reproduce:

1. Launch the forge.
2. Open up an Orc Marauders army.
3. Add an Orc Mob.
4. Select Carbines in the "Replace all Pistols and CCWs with one".
5. Observe the description.

Expected Results:
The Mob now has
```
[10] Carbines 18" A2
[10] CCWs - A1
```

Observed Results:
The Mob now has
`[10] Carbines 18" A2 CCWs (A1`

Notes:
It looks like the CCWs are being treated like a Special Rule (supported by the fact that there is an empty tool tip for "CCWs (A1").  I'm betting a parenthesis got misplaced or it is otherwise being mis-parsed.

**Comment by Darguth** [comment]
It looks like the source data from WC has been fixed, as this now appears to function as expected.

![image](https://user-images.githubusercontent.com/8975633/139728729-236ecde2-962a-4f60-8703-fb9f044063e9.png)
