### ISSUE TITLE
Alien Hive - Some units with Multiple Razor Claws (N x Razor claw) only get applied 1 x Razor Claw

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#144]
For the GF Alien Hive roster, some units with multiple Razor Claws will only get 1 applied on the right tile when editing, this also when viewing the cards only shows up as one. 

The correct amount of Razor Claws to apply are shown on the left hand tile (see example scenario below), however, when translating over they do not appear in the middle tile, or right tile correctly (see example scenario below).

Example Scenario - 'Burrower'

![image](https://user-images.githubusercontent.com/93403931/139596633-ca377190-c937-4210-a64a-cc1368dfedb6.png)
PDF for v2.5 shows 4 x Razor Claws

![image](https://user-images.githubusercontent.com/93403931/139596692-f92e4033-2260-45e8-b797-2952315da540.png)
Left hand tile shows 4 x Razor Claws

![image](https://user-images.githubusercontent.com/93403931/139596705-740cdf87-c473-4b99-939e-e46991a76d29.png)
Middle tile showing 1 x Razor Claw

![image](https://user-images.githubusercontent.com/93403931/139596714-8f460b49-1521-4674-83cf-ff7df6bdd58a.png)
Right hand tile showing 1 x Razor Claw (this is not a visual glitch for this tile, as only 1 'Razor Claw' may be changed using the options, and the 1 x Razor Claw carries over to the cards.

The units affected by this problem are:

- Carnivo-Rex
- Psycho-Rex
- Devourer Beast
- Artillery Beast
- Tyrant Beast
- Spawning Beast
- Burrower

**Comment by AdamLay** [comment]
Thank you - this has been resolved.
