### ISSUE TITLE
Battle Brothers - Master Brother upgrades break when selecting upgrades (cannot regress dependent upgrades)

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#145]
Regression isn't possible and breaks the unit's upgrades/leaves with no equpiment on the Master Brother unit.

When selecting the Master Brother, and choosing to replace the 'Heavy Rifle + CCW' with the 'Heavy Pistol + CCW'

![image](https://user-images.githubusercontent.com/93403931/139597213-8c35d3b4-acb8-4843-a2af-763aa2ce1dff.png)
![image](https://user-images.githubusercontent.com/93403931/139597239-ccaee077-1720-478b-a237-d4c84dc39c3e.png)

then selecting the 'combat shield' upgrade (replacing the 'Heavy Pistol') 
![image](https://user-images.githubusercontent.com/93403931/139597249-bd38a2f2-3dd2-4445-a011-1ed1eebb6295.png)

then selecting the 'Dual Energy Claws' (should replace the 'Heavy Rifle + CCW', it lets you click to select, but then breaks/doesnt allow for some upgrades after)
![image](https://user-images.githubusercontent.com/93403931/139597302-17116db3-7b90-4d6b-bef8-405165d83926.png)

If you then get rid of the 'Combat Shield' then you get left with no upgrades that you can select, and no weapons on the unit :( 
![image](https://user-images.githubusercontent.com/93403931/139597360-ceb110d3-e096-4f7a-999b-b48ffeb9c45e.png)

Don't know whether this should be left as 'user error' since they can delete the unit and start new, also that fixing it by adding regressive calculations for what should be possible would be a large task and low priority, but thought it was worth mentioning as an issue

**Comment by Darguth** [comment]
Fixed and tested. Now if you change a parent/root upgrade option all of the dependent child options are cleared.
