### ISSUE TITLE
Battle Brothers - Upgrade "G" incorrectly visually labelled

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#146]
the Battle Brothers - Upgrade "G" Replace any heavy Rifle and CCW (on the v2.5 pdf) is showing as Replace all Heavy Rifle and CCW on the army-forge (although still works like Replace any, just a visual typo)

**Comment by Darguth** [comment]
AF appears to be functioning fine. I think this is a WC issue and have logged it in that repo's backlog..
