### ISSUE TITLE
Copy Unit Feature

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#149]
**User Story**
As an army list builder
I want to be able to copy the exact details of an existing unit into a new instance of that unit type
So that I don't have to manually create a bunch of similarly equipped units.

**Acceptance Criteria**
- [ ] Action in the list builder pane that allows you to copy any existing unit.
- [ ] Newly created unit is created directly below the copied unit in the list.
- [ ] Some indication is provided to the user that the copy took place (focus is given to it, a toast message is displayed etc.)
- [ ] If the copied unit was Doubled/Combined in size, the new unit is also Doubled/Combined in size.
- [ ] The copied unit has the exact same upgrade options selected as the parent unit.
- [ ] If the copied unit had a custom name, the new unit also has the same custom name.
- [ ] If the copied unit was joined by a Hero the new unit is _**NOT**_ joined by that hero as well.
- [ ] If the copied unit was a Hero and it joined a unit, the new Hero is _**NOT**_ joined to any units.

**Comment by BaptisteD** [comment]
I'm thinking of replacing the delete button on units for a "..." where we could have "Edit, Duplicate and Remove"

**Comment by BaptisteD** [comment]
So here's what I have in mind for this evolution. 

<img width="588" alt="Capture d’écran 2021-11-09 à 17 45 52" src="https://user-images.githubusercontent.com/2566847/140968241-4232f1fc-4221-4e96-985e-fe6df427ea97.png">

**Comment by BaptisteD** [comment]
The "..." button should be active, therefore in blue plz. See the mockup just above.

**Comment by AdamLay** [comment]
Done this - thanks!

**Comment by BaptisteD** [comment]
https://user-images.githubusercontent.com/2566847/159501303-787963b8-4196-46f3-94da-9abb83c280ff.mp4

Weird auto-scroll behavior when tapping on the unit's more menu
