### ISSUE TITLE
Make weapon count formatting consistent

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#151]
When formatting the weapon counts in the upgrade unit pane, always use the format of `<number>x <weapon name>` i.e. `10x Hand Weapons`. Right now it's a hodgepodge of that format, bracketing or both. For example in the TAO Coalition Battle Suits unit it begins with 3 models with 3 Plasma Rifles each. This should display as `9x Plasma Rifles` and not `[3] 3x Plasma Rifles`.

**Acceptance Criteria**
- [ ] Always list the total weapon count, not a `[3] 3x` style format it should be `9x`.
- [ ] Follow the `#x Weapon` format in all cases except a single instance of a weapon, which should just be `Weapon` with no count prefix.

**Comment by AdamLay** [comment]
This is done
