### ISSUE TITLE
EPIC: Matchside Game Aide

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#152]
This is a high-level epic to capture functionality we might want to consider. It will need to be broken down into individual user stories with some thoughtful design work.
1. Damage tracking
2. Activation status tracking
3. Pinned/Stunned status tracking
4. VP tracking
5. Turn tracking
6. Contextual dice rolls (i.e. click on Defense value and enter # of dice to roll and it automatically inflicts damage equal to number of failed saves, stuff like that.)

**Comment by AdamLay** [comment]
As much as I had originally enjoyed this idea - I think this is out of scope of what Army Forge has become. Thanks though!
