### ISSUE TITLE
Display unit size in the card view

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#153]
We should list the unit size for any units with a size > 1 in the card view. This becomes even more relevant with the support for combined units where the size may vary for units with the same name within a roster.

![image](https://user-images.githubusercontent.com/8975633/139741479-1e66b71b-143c-4321-a64d-6b35b8fb2e7c.png)

**Comment by BaptisteD** [comment]
Yep totally agree with you on this !  👍
