### ISSUE TITLE
Battle Sisters (and probably other rosters) - Heavy Rifle Mods available even when no Heavy Rifles are taken

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#154]
This can be replicated by using the Vanguard Sisters, and changing all the weapons to 3 shotguns, 1 storm rifle, 1 heavy pistol, then still being able to take the Heavy Rifle Mod

**Comment by JamJar152** [comment]
Also can be done on Biker Sisters

**Comment by AdamLay** [comment]
Closing as #190 has more info and it's the same issue - thank you!
