### ISSUE TITLE
Need close button on the Display Settings menu.

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#155]
Currently have to click off the menu pane which is awkward. Should put a close button in upper right or something.

![Screenshot_20211101-180225_DuckDuckGo](https://user-images.githubusercontent.com/8975633/139748432-5c11db02-2647-48d7-829e-5853efedb67b.jpg)

**Comment by BaptisteD** [comment]
This is a quite common pattern on mobile though. 
You nearly never have a cross to close menus 

![Screenshot_20211102-010220](https://user-images.githubusercontent.com/2566847/139758120-61d32ba1-ad55-410c-8c36-8802d30d7027.jpg)

**Comment by BaptisteD** [comment]
But, on desktop it is less common to have that without a cross. 
So we could have the side menu as is on mobile, and on desktop add a cross. 

Like here

![unnamed](https://user-images.githubusercontent.com/2566847/139849648-99f05bd6-52f5-474a-bdf6-9629db86e103.png)
