### ISSUE TITLE
Custodian brothers - Anti-Grav Battle Tank has the 'Twin bolt Cannon (30" ' special rule

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#156]
As stated in title, unsure whether this one is a source data problem or army-forge issue, see screenshot below

![image](https://user-images.githubusercontent.com/93403931/139750832-26d9f879-559f-4f41-b393-c0b807c3824a.png)

![image](https://user-images.githubusercontent.com/93403931/139750847-62dd7a50-4941-4afe-a36b-e0c1f1755a42.png)

**Comment by Darguth** [comment]
This is likely a problem with the source data, moving it to the WC backlog: https://github.com/schnick3rs/opr-web-companion/issues/58
