### ISSUE TITLE
Last letter of custom unit name doesn't appear

### ISSUE THREAD

**Issue by X00181735** [AdamLay/opr-army-forge#158]
The last letter of a custom unit's name doesn't appear in the middle column that lists all units already selected, UNLESS you then delete the name, upon which it will update. See images below:

**I choose a unit**
![image](https://user-images.githubusercontent.com/91834269/139828177-e00c9cf1-861f-4ebe-bed5-e62a8d325aea.png)

**I edit its name, notice the last letter is missing in the middle column**
![image](https://user-images.githubusercontent.com/91834269/139828217-e8124a5b-ee17-46ae-b479-45eabd3ab751.png)

**I clear the units name, now the final letter appears**
![image](https://user-images.githubusercontent.com/91834269/139828275-9dc0f800-ba06-4cc4-a76d-6c48dad0943d.png)

**I press the edit pencil, bringing the name back on the right, this time with the final letter in the middle column**
![image](https://user-images.githubusercontent.com/91834269/139828311-7884b9d8-7694-4b91-b301-db4663acacaf.png)

**Comment by AdamLay** [comment]
Thank you for this - good spot! This has been resolved.
