### ISSUE TITLE
Titan Lords Preceptor Titan Pulse Laser Range in wrong column

### ISSUE THREAD

**Issue by ScornMandark** [AdamLay/opr-army-forge#159]
The range shows up in the special rules section, with no tooltip.  

![Screenshot_20211102-074945_Chrome.jpg](https://user-images.githubusercontent.com/7913700/139840918-26cd118a-7ab2-4178-9192-9f08ffb52194.jpg)

**Comment by Darguth** [comment]
This is very likely a problem with the source data, moving to the WC backlog as https://github.com/schnick3rs/opr-web-companion/issues/57.
