### ISSUE TITLE
Robot Legions: "Royal March Order" tooltip missing

### ISSUE THREAD

**Issue by RobMayer** [AdamLay/opr-army-forge#162]
It's in the JSON, but for some reason doesn't appear to be rendering. I poured through what I could in the code, but without diving deeper to try to grok it I can't for the life of me figure out why it's not.

**Comment by Darguth** [comment]
@RobMayer it seems to work for me? Is this what you mean, or is it a different unit/upgrade/rule?

![image](https://user-images.githubusercontent.com/8975633/139933983-b558fdfc-08df-418d-ba55-10d00b2a923d.png)

**Comment by RobMayer** [comment]
Different upgrade.
check the Tripod Walker's Tripod Queen upgrade.
