### ISSUE TITLE
Orc Marauders - Can only select one Bomb Beast

### ISSUE THREAD

**Issue by SquaredSee** [AdamLay/opr-army-forge#166]
I did not see this in the issue list, feel free to delete if this is a duplicate.

I noticed that the Bomb Beast option for the Specialist Orcs says "Upgrade up to two models", but only offers an option to add a single beast.

Edit: After posting I realized this is the same for the Rocket Launcher option on the same page, so I assume this is already known.

![image](https://user-images.githubusercontent.com/22715939/139928008-9da920bc-b336-4a50-9d09-44b771e134e5.png)

**Comment by SquaredSee** [comment]
The update today fixed the Bomb Beast, but the "Replace all up to two Rocket Launchers:" is still a typo. Thanks!

![image](https://user-images.githubusercontent.com/22715939/140134019-cb5e8138-38d3-4e38-9c67-39d4590dc022.png)

**Comment by AdamLay** [comment]
Thank you!
