### ISSUE TITLE
HEF Anti-Grav APC upgrade count incorrect

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#167]
**Steps to Reproduce**
1. Make a High Elf Fleets roster.
2. Add an Anti-Grav APC.
3. Take the `2x Shard Cannons` option.
4. Try to take 2 options from the `Replace any Shard Cannon` upgrade list. It only lets you replace 1, not both.

![image](https://user-images.githubusercontent.com/8975633/139930849-9349f2f1-8f53-4615-b1e2-e9a972b37ff1.png)

**Comment by LukasBroetje** [comment]
I looked up the army book of the HEF and there should be no way to replace a
![HEF](https://user-images.githubusercontent.com/16824390/140608296-180dc49b-2094-45e7-a6e0-e31f6f7860f7.PNG)
 shard cannon with one of the options but a twin shard cannon should be an option "upgrade with one" and the other options, too. See HEF v2.10, page 3, upgrades B.

**Comment by BaptisteD** [comment]
Keep in mind that the PDFs are no longer up to date and that OPA made several changes since the preview PDF of the 2.5.
