### ISSUE TITLE
TAO Battle suit drone selection

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#169]
When taking Tao battle suits the stone selector is a little funky. Image is for a double unit. Says any model can take up to four and only has a max selection of 2 not 24 like listed or 12 as I imagine is the intent.
![image](https://user-images.githubusercontent.com/4223668/140032745-839d7767-efa1-4b77-8734-04740cb585ab.png)

**Comment by BaptisteD** [comment]
@AdamLay  Probably not possible anymore since the rework of the Combine Units behavior. 

BUT, the bug remains for units like **Battle Suits(3)** which should be able to take up to 6 drones and can only take 2 today.
