### ISSUE TITLE
TAO Battle Suit upgrade Energy Shield adds 'Shield Wall' but this has no info.

### ISSUE THREAD

**Issue by scudmarx** [AdamLay/opr-army-forge#176]
![ShieldWall](https://user-images.githubusercontent.com/23005404/140165715-f10f9b48-2929-4b06-ad5c-cf7f464a2b9f.png)

**Comment by scudmarx** [comment]
The Battle Suit Elite's energy shield upgrade also has no rules text/tooltip, though in this case it is less... important?
![BossManShield](https://user-images.githubusercontent.com/23005404/140166713-fe3c517e-dec7-46cf-8740-e0ca1ada7e65.png)

**Comment by BaptisteD** [comment]
Army Forge only shows the text sent by OPA so we can't do anything ourselves. (I'll close this issue then)
He's been ping on the subject.
