### ISSUE TITLE
HDF Veterans combined unit size not updating properly

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#178]
**Steps to Reproduce**
1. Make and HDF roster
2. Add a unit of Veterans
3. Click `Combined Unit`.
EXPECTED: Unit size of the combined unit should be [10].
ACTUAL: Unit size lists as [5].

![image](https://user-images.githubusercontent.com/8975633/140172937-ce247fbd-7e47-464c-a336-93900e437d54.png)

**Comment by AdamLay** [comment]
Resolved thank you
