### ISSUE TITLE
Battle Brother detachments save to local storage but don't appear in saved army list

### ISSUE THREAD

**Issue by X00181735** [AdamLay/opr-army-forge#183]
Battle Brother detachments save to local storage but don't appear in saved army list

Please see below

![image](https://user-images.githubusercontent.com/91834269/140320070-c0c547c3-55ad-486d-a7dd-b03269dc4bf6.png)

**Comment by Jones-UI** [comment]
I noticed the same issue with Havoc Brothers lists.

**Comment by Jones-UI** [comment]
More info:
I am seeing this behavior with "regular" Battle/Havoc Brothers lists also, not just Detachments/Disciples.
Seems to only affect "Auto-Save" lists.

**Comment by Jones-UI** [comment]
Also seeing the same behavior with Wormhole Daemons.
