### ISSUE TITLE
Havoc Brothers "Disciples" choice is typo'd to "Desciple"

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#187]
when you click on the Havoc Brothers army (create new) then it lets you choose which Disciples to choose, the Disciples sub-heading at the top is typod. As shown below

![image](https://user-images.githubusercontent.com/93403931/140610009-7ce4981f-e985-4d06-bfcf-d9aa04bff8a5.png)

**Comment by BaptisteD** [comment]
Also, the "None" option should always be the first of the list.
