### ISSUE TITLE
Orc Battle Rig Cant Replace All Rocket Lauchers with Heavy Machine Gun

### ISSUE THREAD

**Issue by thorlek001** [AdamLay/opr-army-forge#188]
In the Orc Battle Rig Cant always Replace All Rocket Lauchers with Heavy Machine Guns... and sometimes when you remove the 2x Rocket Lauchers upgrade, you lose ALL Rocket Launchers.

Steps to Reproduce
Add a Battle Rig to your list (it comes with 4x Rocket Launchers)
Add the 2x Rocket Launchers Upgrade (You now have 6x RLs)
Try to use Replace Any RL to change to 6x Heavy MGs (you can only get to 5x MG and 1x RL)  **BUG HERE**
Remove all the Heavy MGs (You now have 6x RLs)
Remove the 2x Rocket Lauchers Update (You now have Zero RLs) **BUG HERE**
 

![image](https://user-images.githubusercontent.com/93825802/140610113-fbab0df2-133f-4222-b197-9e7a3d1c49a3.png)

**Comment by thorlek001** [comment]
This might be related to #167 
Possibly the code that reads the "Nx Rocket Lauchers" is parsing text incorrectly? I not that in both issues the text will change from   Rocket Laucher or Shard Cannon to Nx Rocket Laucher**s**   (note the s being added when there are multiple)

**Comment by AdamLay** [comment]
Fixed - thank you! :)
