### ISSUE TITLE
Add number of remaining available weapons for "Replace any..." upgrades

### ISSUE THREAD

**Issue by BaptisteD** [AdamLay/opr-army-forge#189]
For "Replace any..." upgrades we should add the number of the remaining available weapons. 
Something like : Replace any Plasma rifle (3)

**Comment by AdamLay** [comment]
@BaptisteD thanks! Good idea. Not sure it works so well with Radio Groups - what do you think?
![image](https://user-images.githubusercontent.com/4223668/159442997-f82fbee0-fee7-468f-a554-a32352a32946.png)

**Comment by AdamLay** [comment]
Otherwise it is quite handy! 
![image](https://user-images.githubusercontent.com/4223668/159443072-d9ad3b42-4b2b-4a4f-a1e2-ed0cf8e7585b.png)
