### ISSUE TITLE
Multiple Armies - "Any model may take one Heavy Rifle attachment" only allowing 1 upgrade

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#191]
The Havoc Brothers - Havoc Destroyers unit has multiple issues, one of the issues is they can take the "Heavy Rifle Attachments" options whilst not heaving a "Heavy Rifle", same problem as Ticket #190 and so completely fixing this issue will be dependent in part on the solution for Ticket #190.

The other issue is the Havoc Destroyers have an "Any model may take one Heavy Rifle attachment" option, except even with multiple Heavy Rifles in the unit (as shown on screenshot below) you can only upgrade one model with a Heavy Rifle attachment.

![image](https://user-images.githubusercontent.com/93403931/140611453-336d7b29-3e1a-4937-98e2-9f37dba0b774.png)

**Comment by JamJar152** [comment]
Same issue for Change Destroyers

**Comment by JamJar152** [comment]
Same issue for Lust Destroyers

**Comment by JamJar152** [comment]
Same issue for Plague Destroyers

**Comment by JamJar152** [comment]
Same Issue for War Destroyers

**Comment by AdamLay** [comment]
@JamJar152 I think this one is resolved - can you double check please? Don't need to check all the units - behaviour will be the same for all, thanks

**Comment by JamJar152** [comment]
@AdamLay Yep this issue is fixed, tested on all 5 and everything works as intended (cannot take attachments without Heavy Rifle + there is now the correct amount per models in the unit)
