### ISSUE TITLE
Multiple Armies - "Upgrade any Brute Fist with one" rule lacking dependency check

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#192]
Similar to Ticket #190, with the Havoc Brothers - Infernal Brute unit you can swap out all Brute Fists (shown below)

![image](https://user-images.githubusercontent.com/93403931/140611526-58982276-a676-4436-8a3e-68ea81b51d46.png)

and still be able to select the "Upgrade any Brute Fist with one" option (shown available to select below)

![image](https://user-images.githubusercontent.com/93403931/140611541-8e3e4f87-08ea-494e-bbe5-f2f7a8e5ac44.png)

Leading to the final screenshot below after selecting an upgrade

![image](https://user-images.githubusercontent.com/93403931/140611569-16d9aaf3-94b8-4062-83f7-af6b466e2a31.png)

**Comment by JamJar152** [comment]
same issue as Change Infernal Brute

**Comment by JamJar152** [comment]
Same issue for Lust Infernal Brute

**Comment by JamJar152** [comment]
Same issue for Plague Infernal Brute

**Comment by JamJar152** [comment]
Same issue for War Infernal Brute

**Comment by AdamLay** [comment]
Thank you this has been sorted - just to note it's not the same as #190 though as "attachment" upgrades work differently. Thanks,
