### ISSUE TITLE
Human Inquisition - Private Guard - Losing weapons when reverting upgrades

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#197]
for Human Inquisition - Private Guard - if you follow the steps below, then for some reason when you revert the steps afterwards you lose 1 x Rifle + 1 x CCW (this is repeatable).

Step 1) 
select 2 Plasma Rifles in the "Replace up to two Rifles" upgrade
![image](https://user-images.githubusercontent.com/93403931/140647959-989aaa79-f468-4423-b3c5-cf536308ea80.png)

Step 2) 
select the Pistol in the "Replace one Rifle and CCW" upgrade
![image](https://user-images.githubusercontent.com/93403931/140648008-7edd7592-4951-4033-828c-03a5deae6f95.png)

Step 3)
Select the Plasma Pistol in the "Replace one Pistol" upgrade
![image](https://user-images.githubusercontent.com/93403931/140648028-c71ffb61-931e-42e7-abea-24fa339b5b8a.png)

Step 4)
Select the Energy Sword in the "Replace one CCW" upgrade
![image](https://user-images.githubusercontent.com/93403931/140648045-84d7eba3-260c-49ab-81e2-7adf0a004250.png)

Step 5)
Revert the upgrades from Step 1 - 4 in the order: Step 4 -> Step 3 -> Step 2 -> Step 1
i.e., (Replace one CCW (back to none), Replace One Pistol (back to none), Replace one Rifle + CCW (back to none), Replace up to two rifles (back to 0 plasma rifles)).

![image](https://user-images.githubusercontent.com/93403931/140648109-6dfbcb29-e651-4cde-bf52-ae608695f578.png)

**Comment by AdamLay** [comment]
Fixed!
