### ISSUE TITLE
Mark or hide options not available for current chosen one for an unit.

### ISSUE THREAD

**Issue by arcanelviejo** [AdamLay/opr-army-forge#198]
It would be an improvement to hide or mark (for instance, strike) options than are not possible to chose for the current configuration of an unit.

**Comment by arcanelviejo** [comment]
I just saw that the shade of grey of the selection "circle" is a bit different when possible to select or not given the current choices, but barely noticeable (at least in my browser, firefox). Making the difference more visible would be enough to achieve what i had in mind with the posted suggestion; perhaps putting in other color, like blue, the clickable circle options.

**Comment by BaptisteD** [comment]
Yeah alright I get that. 
Indeed we can put the available options in blue as all interactive elements in army forge are in blue. I will close this issue and create a new one dedicated to this change.
