### ISSUE TITLE
Suggestion to initial random list generator

### ISSUE THREAD

**Issue by arcanelviejo** [AdamLay/opr-army-forge#200]
Suggestion for an initial random list generator, possible guidelines based and dependent on competitive list validation #77 :

1. Select army_points: 500, 1000, 1500, 2000,  possible_to_select_unit set to true 
2. Loop while total_selected_points <= army_points  and possible_to_select_unit
   2.1 iteration_points = min( 500, army_points - total_selected_points)
   2.2 Select random hero or go to next until possible to add (if enough  iteration_points and validation check)
   2.3 Select random unit non hero or go to next until possible to add (if enough  iteration_points and validation check)
   2.4 Join hero selected in iteration to unit (if both exists and validation checks)
   2.5 check if any unit has been added this iteration and updates possible_to_select_unit and total_selected_points

As it can be seen, no upgrades nor combined units are addressed, but it can be added later.

**Comment by AdamLay** [comment]
This is a cool idea, but I can't see us implementing it - thank you for the suggestion!
