### ISSUE TITLE
Change the color of active radio buttons 

### ISSUE THREAD

**Issue by BaptisteD** [AdamLay/opr-army-forge#203]
In all Army Forge, switch the current grey color for available options radio button to the Army Forge blue. 

The unavailable options stay in the light grey that we currently have. 

The goal is to help users see a bit more clearly the available options in the upgrade panel.

**Comment by Jones-UI** [comment]
It might be preferable to gray-out the text **and** the radio button circle of unavailable options.
This would make the available options more apparent while keeping the selected option as the most visible.

**Comment by BaptisteD** [comment]
Indeed, that's what has been done for the BB Detachements when we had to. 

So, grey out text and radio buttons for unavailable options. 
Make the radio buttons for available options blue.

**Comment by Jones-UI** [comment]
I would suggest making available radio button circles black (instead of gray) and reserve blue only for the active selection.

**Comment by BaptisteD** [comment]
All interactive elements in AF are in blue so I would prefer that we stay consistent with that. 
For active radio buttons we have a different state (a filled one).   :)

**Comment by Jones-UI** [comment]
@BaptisteD  I think we are on the same page.
This is what I was trying to describe:
![AF-radio-buttons](https://user-images.githubusercontent.com/51341116/141593734-1f5f0b42-5ccd-42d2-a994-b92e4184c6d2.png)

**Comment by BaptisteD** [comment]
Good idea to make a mockup.  ^^
Always simpler to talk with an image. 

So, yeah I understood that. I'm saying that imo "available options" buttons should be in blue.  :) 
If you look at the above picture, the available arrows are in blue. (So the checkboxes should follow the same pattern). 

![Screenshot_20211113-102502](https://user-images.githubusercontent.com/2566847/141613635-da73d369-6e6f-4ee4-b0be-1fb8c165aeb9.jpg)

**Comment by Jones-UI** [comment]
Okay, I get your logic now :)
![AF-radio-buttons-blue](https://user-images.githubusercontent.com/51341116/142496382-b92003d6-0784-4bd6-b183-edb6e4e19b61.png)

**Comment by BaptisteD** [comment]
Yeah, that was it.  :) 
Adam implemented the disable part of it, but the active one will stay in black for now (technical limitations). 
But with the greyed out text and button it's already way better to see in a glimpse what's active and what's not.

**Comment by BaptisteD** [comment]
Current dev state is considered as good enough so I close this one.  :)
