### ISSUE TITLE
Orc Marauders - Multiple Units - "Any model may take one Carbine attachment" option is broken

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#212]
The Orc marauders - Boss Mob unit, has the "Any model may take one Carbine attachment" option, however, the maximum amount of upgrades is 1 (there are 5 models in the unit). This unit also has the #190 issue which may need to be compatible with the "Any model may take one Carbine attachment" option.

Step 1) Take the maximum amount of upgrades for the "Any model may take one Carbine attachment" option.

![image](https://user-images.githubusercontent.com/93403931/140999627-1954d38f-104c-4845-9cad-747c0a59278b.png)

**Comment by JamJar152** [comment]
This bug also happens for the following units:

- Ultra Bosses

**Comment by thorlek001** [comment]
Theres actually another issue here, in the screen shot above, you have 5x Pistols so no Carbine Attachments should be avaiable... but you can select one.

If you add 5 carbines, you ushould be able to add 5 carbine attachments... but as per this ticket you can still only select 1 carbine attachment.

**Comment by arcanelviejo** [comment]
Same issue #229. Problem seems in dependencies definition of gains in data of upgrade.

**Comment by JamJar152** [comment]
This issue has been partially fixed (fixed for the Boss Mob), however, the same issue still occurs for the Ultra Bosses similar to the issue in #190. 

After taking 3 Heavy Rifle Attachments (correctly), swapping the Heavy Rifles for 'Dual Ultra Saws' does not remove the Heavy Rifle Attachments.

Step 1) Take 3 of the Carbine attachments from the 'Any model may take one Carbine attachment' option
![image](https://user-images.githubusercontent.com/93403931/142269077-749aef43-2c36-4e97-b883-f4589a7c2de0.png)

Step 2) use the 'Replace any Carbine and CCW' option and replace all carbines with 'Dual Ultra Saws'
![image](https://user-images.githubusercontent.com/93403931/142269284-38cf88b3-0281-4287-8d9c-78492ad0954f.png)
