### ISSUE TITLE
Rebel Guerrillas - Multiple Units - "Upgrade with any model" option has no maximum upgrade limit + doesn't show the amount of Spotting lasers

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#213]
Rebel Guerrillas - Spotter - "Upgrade with any model" option has no maximum upgrade limit for the "Spotting Laser", when you add more than 1 spotting laser there is no graphical change to show how many spotting lasers have been added. Similar issue to #202 but more complex

Steps to repeat

Step 1) Choose 10 Spotting Lasers in the "Upgrade with any model" option

![image](https://user-images.githubusercontent.com/93403931/141008006-f0a8d83a-ca3c-4616-bdd8-ce6794c35bb7.png)

![image](https://user-images.githubusercontent.com/93403931/141008046-1789da3c-fe50-4d50-ae64-19b57056ba8c.png)

**Comment by JamJar152** [comment]
This problem also happens for:
Rebel Guerrillas - Simians - "Upgrade with any model" option "Claw Gauntlets" has no maximum limit (should be 3 as there are 3 models in the unit)

![image](https://user-images.githubusercontent.com/93403931/141008812-cc92ad15-2fce-4570-8c06-746d2b949211.png)

**Comment by AdamLay** [comment]
Thanks @arcanelviejo - that has sorted the behaviour! Will leave this open until we work out what to do about the display count.

**Comment by AdamLay** [comment]
OK added the count - resolved, thanks
