### ISSUE TITLE
TAO Heavy Stealth Suit doesn't show count of drone upgrades

### ISSUE THREAD

**Issue by thorlek001** [AdamLay/opr-army-forge#215]
TAO Heavy Stealth Suit doesn't show how many drones

You can add up to 2 drones to a Heavy Stealth Suit, but regardless of how many you select it only lists "Stealth Drone" in the special rules, it should say "2x Stealth Drone" if there are two them, because the cost and benefit stacks

![image](https://user-images.githubusercontent.com/93825802/141237030-9a028e19-3404-4a57-b336-d0c9ef2ad408.png)

**Comment by AdamLay** [comment]
Thank you - resolved
