### ISSUE TITLE
HEF AntiGra Tank: Upgrade Two Weapons to One

### ISSUE THREAD

**Issue by projape** [AdamLay/opr-army-forge#217]
HEF Anti-Grav Tank: 
- Standard 2x Twin Shard Cannons
- Upgrade-Action: Replace 2x Twin Shard Cannons
- Upgrade with Prism Cannon
- Result: 2x Prism Cannon in units weapon list

best solution: should be a radio button with a none-option, 2x should be treated as one in this case
proposed solution: keep as is, but remove '2x' from units weapon list, as only one Prism Cannon is tak
![HEF_AntiGraTank_PrismCa](https://user-images.githubusercontent.com/57186997/141307341-29160b1d-64a4-4458-bd07-f2b6d66c1b4b.png)
en

**Comment by arcanelviejo** [comment]
Suggestion: Change Rule from "Replace 2x Twin Shard Cannons" to "Replace all Twin Shard Cannons with one" or ""Replace all 2x Twin Shard Cannons with one"", if possible.
