### ISSUE TITLE
Robot Legion - Chained Tyrant Monolith - Psychic Master special rule needs psychic spell list

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#220]
The Chained Tyrant Monolith unit for the Robot Legion roster has the special rule "Psychic Master" ( 'This model counts as having the Psychic(2) rule, and may cast or block up to 3 spells each round, however whenever it fails to cast a spell, it takes 3 wounds' ), however, the unit doesn't have the psychic spell list with the option on.

![image](https://user-images.githubusercontent.com/93403931/141366012-f6467d02-df18-4b96-981b-fc0f72dbb697.png)

**Comment by AdamLay** [comment]
Just going to scan the rules text...
