### ISSUE TITLE
Multiple Armies (presumably) - combining multiple rule instances breaks adding tough values

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#221]
As the title states, this probably affects multiple armies. The new update for combining multiple upgrades of the same kind (#202 or similar) has broken atleast the toughness upgrade for the Soul-Snatcher Cults - Cult Champion unit. The "Upgrade with" 'Combat Bike (Fast, Tough(+3))' will now combine the added toughness so it states 2xTough(6). Screenshot below

![image](https://user-images.githubusercontent.com/93403931/141368991-b16b7b1f-0d93-487a-ab62-0dfb379501a2.png)

**Comment by AdamLay** [comment]
Thank you - fixed! :D
