### ISSUE TITLE
TAO Coalition - Battle Suits - "Upgrade any model with up to two" only allowing 1 models worth of upgrades (3 models in unit)

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#224]
the TAO Coalition - Battle Suits - have an "Upgrade any model with up to two" option, however, currently the maximum amount of upgrades allowed is 2 (should be 6 (2 x 3)).

![image](https://user-images.githubusercontent.com/93403931/141375562-9623a030-47c4-4b16-a8c9-28dd53371fa9.png)

**Comment by AdamLay** [comment]
Resolved - thank you!
