### ISSUE TITLE
Wormhole Daemons of War - Greater Daemon of War - Incorrect weapon name "Exalted Flame Axes"

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#228]
The Wormhole Daemons of War - Greater Daemon of War - has the incorrect weapon name "Exalted Flame Axes", instead of "Exalted Flame Axe". Originally i thought this was a WC issue and so directed it towards OPA, but he confirmed it is called "Exalted Flame Axe" in WC (screenshot below). The "Replace any Exalted Flame Axe" upgrade is unusable as the name is currently incorrect

![image](https://user-images.githubusercontent.com/93403931/141646025-c7d4848a-315e-4ebb-be96-8e3cb111c07c.png)
(#army-forge channel - 13/11/2021 1:38 GMT)

![image](https://user-images.githubusercontent.com/93403931/141646050-66d566e4-6f24-4c17-867d-50534ea44f0f.png)

**Comment by AdamLay** [comment]
Thank you! :)
