### ISSUE TITLE
Prime brothers (+ all derivative armies) - Prime Brothers - "One model may take one Auto-Rifle attachment" upgrade stays even when "Auto Rifle" is removed

### ISSUE THREAD

**Issue by JamJar152** [AdamLay/opr-army-forge#229]
The Prime Brothers ( and all of the derivative rosters) - Prime Brothers (or equivalent per roster) may take the "One model may take one Auto-Rifle attachment" upgrade, this upgrade can only be taken when there is an "Auto-Rifle" weapon (otherwise it is greyed out), however, once the "Auto-Rifle" is removed, the Attachment upgrade still stays. Steps to replicate

Example used Blood Prime Brothers:
Step 1)
Use the "Replace any Heavy Rifle" option to take an "Auto-Rifle"
![image](https://user-images.githubusercontent.com/93403931/141648500-62f134b1-dedc-4002-9cd4-ca6b4198186a.png)

Step 2)
Use the "One model may take one Auto-Rifle attachment" option to add a "Grenade-Mod"
![image](https://user-images.githubusercontent.com/93403931/141648530-f5834113-eae3-40da-8609-dc29c49f596b.png)

Step 3)
Remove the "Auto-Rifle" from the "Replace any Heavy Rifle" option
![image](https://user-images.githubusercontent.com/93403931/141648551-5cded287-ffeb-471d-ad20-a3caaaa030cc.png)

**Comment by arcanelviejo** [comment]
Same issue with #212.  Problem seems in dependencies definition of gains in data of upgrade.

**Comment by JamJar152** [comment]
Tested on multiple versions of 'Brothers' units, issue with this ticket is fixed.
