### ISSUE TITLE
Missing Wormhole Daemons Icon

### ISSUE THREAD

**Issue by Jones-UI** [AdamLay/opr-army-forge#236]
On the "Open a List" page (https://opr-army-forge.vercel.app/load), the Wormhole Daemons icon is missing.

"Could not load the image"
background-image: url("img/gf_armies/Wormhole Daemons of War.png");

**Comment by scudmarx** [comment]
Fetching an image in a 'smart' way like the ArmyImage component does involves using data that isn't currently stored in the save files themselves. The app would need to look into the save to get the armyId, and then use that to fetch the army's image file link from the WebCompanion API. There are several ways this could be achieved, perhaps something @AdamLay might want to consider when he reworks the Save/Load system soon, to enable a more elegant way to do it than using the WC like that.

**Comment by Jones-UI** [comment]
Seeing the same issue with Havoc Brothers icon.
