### ISSUE TITLE
Refreshing the page loses the list I'm building.

### ISSUE THREAD

**Issue by scudmarx** [AdamLay/opr-army-forge#265]
This is a pain.

From VladHerzog on discord:
> Suggestion: disable "pull down to refresh" on mobile so i don't lose my progress while building a list
> (should be doable by adding "overscroll-behavior:none;" to the css for chrome)

And/or, storing (some) state in session storage.

**Comment by AdamLay** [comment]
the list ID is stored in the query string now so this is sorted!
