### ISSUE TITLE
Army Forge: App crashes when trying to change "Replace Pistol" options on GDF Dwarf Lord.

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#27]
Steps to reproduce:
1. Open Army Forge > GDF > Dwarf Guilds
2. Add a Dwarf Lord unit.
3. Select the "Pistol+CCW" replacement option in the first upgrade list.
4. Select any pistol-replacement option from the 2nd upgrade list, such as a Burst Pistol. Works fine.
5. Select any different pistol-replacement option, such as Combat Shield or even None. App crashes with a Type: n is undefined error.

**Comment by AdamLay** [comment]
Upgrade logic has changed to act on the last occurrence of a weapon in the equipment list which has helped with upgrade/replace when used in conjunction with one another!
