### ISSUE TITLE
Radio buttons sometimes multi select

### ISSUE THREAD

**Issue by ScornMandark** [AdamLay/opr-army-forge#272]
![Screenshot_20220211-093730_Chrome.jpg](https://user-images.githubusercontent.com/7913700/153621223-d3c77ebe-0066-4615-8895-93d3bb431bad.jpg)

It seems the army forge has a bug when you get some updates for the ork boss, it activates 3 of the radio buttons, but still counts the points right. Points are right and rules are right, but multi radio buttons.  (I've had that happen on other lists, as well as selecting a church box that grays out other valid selections as well, but that's custom stuff on the staging site so person_shrugging)

It won't let you select any of the additionally selected radio buttons, though, and selecting an unselected one removes all the selected radio buttons and puts it back at none.

**Comment by ScornMandark** [comment]
Additional units have the same problem:
Orc Marauder Commandos (ultra club-ultra claw specifically).  Orc Pirates as well.
![image](https://user-images.githubusercontent.com/7913700/154570001-2ceb21b5-aedb-475a-ae54-5acfc3e1d88f.png)

HDF Light Walker (any selection selects all radio buttons)
![image](https://user-images.githubusercontent.com/7913700/154570249-53f7fa67-6a66-40da-a9fb-ea73c98c6c2f.png)

**Comment by ScornMandark** [comment]
Also shows up alien hives prime warrior ![unknown-3.png](https://user-images.githubusercontent.com/7913700/154805489-ab2c3d91-0094-4342-80ed-fa0fb162f6cc.png)

**Comment by AdamLay** [comment]
@ScornMandark thank you for reporting this - good spot!
@schnick3rs I've traced this back to the fact that some upgrades do not have IDs! can we check the migration script at some point and assign IDs to everything that doesn't already have one? thanks!

**Comment by ScornMandark** [comment]
@AdamLay @schnick3rs Will that fix accommodate custom lists entries as well?  Or will those need additional work? I've encountered the same problems (using the staging site), but I don't know if it's a custom list issue or the same issue.  (I also understand it's pretty far down the punch list lol)

**Comment by schnick3rs** [comment]
@AdamLay @ScornMandark I have rerun the script to ensure the correct IDs for upgrade options. I did a short test and it seem to work, please confirm.

**Comment by ScornMandark** [comment]
@schnick3rs @AdamLay confirmed for logged examples! Some custom things not working properly, but that's for another time lol

**Comment by AdamLay** [comment]
Thanks for confirming - will close the issue. :)
I'm amazed anything custom is working at the moment - don't know how schnickers has it hooked up in the background though. I thought it was a separate database lol!

**Comment by ScornMandark** [comment]
> Thanks for confirming - will close the issue. :)
> I'm amazed anything custom is working at the moment - don't know how schnickers has it hooked up in the background though. I thought it was a separate database lol!

I'm just happy to play with it, and it's very possible it's just how I've got things phrased in the list lol
