### ISSUE TITLE
Combined units double charges for command group

### ISSUE THREAD

**Issue by TechPriest001** [AdamLay/opr-army-forge#274]
## Current Behavior
Selecting any combination of sergeant, musician, and/or standard and checking the "combined" box results in the unit cost charging for these twice. 

## Desired Behavior
It is my understanding from discord server that when creating combined units, you do not buy the command group twice. 

## How to Reproduce
- Version 2.5, select Havoc Warriors. 
- Choose Plague Kings. 
- buy one or more command unit upgrades
- select "combined" checkbox. 
The combined unit cost will reflect the command group charged twice.

**Comment by AdamLay** [comment]
OK interesting - good spot thanks! This is a problem to do with the order in which the upgrade is applied. If you combine the unit and then apply the upgrade, it will only be applied to one of the 2 units.
Agreed this is a problem though - there is another issue for special behaviour for command group upgrades so going to close this one - thank you!
