### ISSUE TITLE
Display profiles for summonable units?

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#283]
GF:
AH: Spawning Beast: Spawn Brood 5x grunts (shoot/assault) or 3x swarms & Mortar Beast: Spores (3x spores/1x big spore)
RL: Spider robot: Release Swarm (2x bot swarms)
WD-C: Pink/Blue warriors: Split/Split again (2x blue warriors & 1x yellow warrior)
WD-L: Infernal Harpist: song of summoning (5x lust warriors)

AoF: 
RD-C: same as GF
RD-L: same as GF
Saur: Ankylosaurus: Serpent Ark (2x snake swarms)
VU: Champion: Raise Dead (5x zombies)

**Comment by BaptisteD** [comment]
Hmm that's a tough one. For the Spawning Beast there is 3 possible choices, that's a lot of infos to display. And if we display them all, we need to be sure that the user understand that he gets access to only one of them.

**Comment by BaptisteD** [comment]
On top of that, this spell can be used at each activation.. (so we can't ask the user which unit he wants when he adds the Beast in his list)
