### ISSUE TITLE
"Upgrade all models with one"

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#284]
Should the Geckos show x5 Blowpipes, as all models get one?

![image](https://user-images.githubusercontent.com/4223668/160560550-5af44a6d-7ac2-4a81-8d95-b3b92498f56d.png)

**Comment by BaptisteD** [comment]
I would say so. They all have 1 CCW each and we show a x5

**Comment by AdamLay** [comment]
Yep this was definitely a bug - currently "Upgrade all" is not handled, this is the first one! At the moment we only handled "Replace all..." :)
