### ISSUE TITLE
Client-side exception when removing army from list while a unit from that army is selected

### ISSUE THREAD

**Issue by Skjolnir** [AdamLay/opr-army-forge#287]
Application error: a client-side exception has occurred (see the browser console for more information).

Repro:
- create any list with multiple armies
- select (not add) a unit from one of them
- edit the list to remove the army you have a unit selected from
- save and observe.
![image](https://user-images.githubusercontent.com/5647119/161433921-0aa68bf2-d6ab-4497-ba6c-8f9216bd5ac1.png)

**Comment by AdamLay** [comment]
Thank you!
