### ISSUE TITLE
Dark Mode!

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#291]

**Comment by MatejKozica** [comment]
I'll do this one

**Comment by MatejKozica** [comment]
Should we get dark mode faction icons for this one? These blueish ones look a little bit strange on dark card.

**Comment by AdamLay** [comment]
Hey @MatejKozica thanks for looking, sorry I missed this! I wonder if we could use CSS to skew the colour - I don't think we'll be able to get a new set of images for this! Thanks,
