### ISSUE TITLE
Unit Notes

### ISSUE THREAD

**Issue by AdamLay** [AdamLay/opr-army-forge#308]
What type of notes do people want to take in a unit. What's the average length, etc. 

That could help to decide a few stuff.
In the meantime, I would advise to have a button "Add notes" rather than a blank area. 
If there is content, just showing the content and an edit button. Really close to what we have to the unit name.
Probably close to the top as it can be important infos. Maybe in the top section, just below the special rules.

**Comment by TBigLyfe** [comment]
°Names for characters + lore details
°Homebrew buffs, upgrades, keywords, weapons, whatever
°Notes on campaign stuff or just unit stuff
°Notes to remember random things or maybe explanations, erratas, etc...
°Mid-game alterations or status, such as wounds, dead/alive, buffs and debuffs, etc...
°Hero upgrades
°Its good to have notes in general, idk about word length but I think between 200-600 is super.
