### ISSUE TITLE
Keywords that appear only in spells are not shown in keyword information

### ISSUE THREAD

**Issue by klauskopec** [AdamLay/opr-army-forge#329]
If keywords (e.g., Furious) only appear in a spell of an army, but not for any units/models/weapons, they are not shown in the keyword summary. It would be great if this could be added.

**Comment by AdamLay** [comment]
[Army_Special_Rules_containing_other_Special_Rules_List.txt](https://github.com/AdamLay/opr-army-forge/files/9001409/Army_Special_Rules_containing_other_Special_Rules_List.txt)
We've been through and identified each rule this should apply to - next step is identifying some patterns to capture rules out of the text, e.g. `get the ([\w\s]+) special rule`
