### ISSUE TITLE
When editing model names, it's uncomfortable to exit edit mode

### ISSUE THREAD

**Issue by klauskopec** [AdamLay/opr-army-forge#337]
To exit name edit mode, we have to click the pencil icon again, which is quite unintuitive. It would be nice to be able to instead 1) press the return key and/or 2) click outside the name input box to exit edit mode.

**Comment by petertbernhardt** [comment]
Looks like clicking outside of the input box does actually exit name edit mode.
So the main fixes here are adding key handlers for the escape and enter keys to close edit mode.

**Comment by AdamLay** [comment]
This has been fixed even though there's no commit against the issue!
