### ISSUE TITLE
Chains of keywords are not fully resolved in the keyword explanation box

### ISSUE THREAD

**Issue by klauskopec** [AdamLay/opr-army-forge#339]
For example, if an AoF Saurian Veteran is upgraded with "temple guard (Ancient Wrath)", the explanation for ancient wrath is correctly added as "The hero and its unit get the Furious special rule." However the keyword Furious which is mentioned inside that rule text, is not added to the explanation box, making the explanation box incomplete unless the keyword is coincidental added because another unit has it as well.

**Comment by AdamLay** [comment]
This is done and released.
