### ISSUE TITLE
AoFS command group options

### ISSUE THREAD

**Issue by LikeANinja** [AdamLay/opr-army-forge#345]
Rules only allow a single Sergeant, banner bearer and musician per army. Remember to take into account any taken upgrades would need to be omitted if a unit is duplicated.

**Comment by klauskopec** [comment]
To clarify: we need this when duplicating (as LikeANinja stated) but also when manually adding multiple of the same command group type. The warning bell for invalid army composition should appear in all of those cases.

**Comment by klauskopec** [comment]
Showing an alarm bell message for this has been implemented if the number of Sergeants + Musicians + Battle Standards is > 1 in an army.

It's not taken into account when duplicating a unit with a command group, but what's been implemented is a good workaround.

**Comment by klauskopec** [comment]
Submitted PR to remove any selected command group when duplicating in AoFS lists.

If this change gets accepted, this issue is fully resolved.
