### ISSUE TITLE
Can't see campaign Talents/Injuries at a glance in Unit Details

### ISSUE THREAD

**Issue by petertbernhardt** [AdamLay/opr-army-forge#347]
You have to expand every section in the talents UI until you find the talent(s) your unit has. There should be a bulleted list showing which ones the unit has, and each bullet point should be hoverable/clickable to show the details
![Screenshot_20220810-190025](https://user-images.githubusercontent.com/3608861/184156958-9de87cf0-247e-4546-82ca-7389dc60f5af.jpg)
.
![Screenshot_20220810-190030](https://user-images.githubusercontent.com/3608861/184157066-94f90984-f51e-43eb-9644-1df444781715.jpg)

**Comment by klauskopec** [comment]
@petertbernhardt this is implemented in the develop branch now and should be publishe with the next release. All selected campaign traits are now shown below the weapons & equipment as a newly introduced "Campaign Traits" section.

**Comment by klauskopec** [comment]
New feature now available in production. @AdamLay feel free to close this issue. 

![Screenshot_20221104-155045_Brave](https://user-images.githubusercontent.com/7880831/200005102-b56f608d-6a5b-42ca-8a0d-cc0ad281a186.jpg)
