### ISSUE TITLE
Injuries in Campaign Mode don't make units cheaper by 5pts each

### ISSUE THREAD

**Issue by petertbernhardt** [AdamLay/opr-army-forge#348]
Talents do this, needs to happen for injuries too

**Comment by petertbernhardt** [comment]
Got a WIP PR but need to learn how to actually edit unit costs

**Comment by klauskopec** [comment]
This has been fixed in the develop branch and should be available when the next version is released.

**Comment by klauskopec** [comment]
Fixed in production. @AdamLay feel free to close this issue.
