### ISSUE TITLE
Several campaign mode skill set texts are wrong

### ISSUE THREAD

**Issue by klauskopec** [AdamLay/opr-army-forge#359]
Almost all of the mouse-over descriptions of skillset in campaign mode are incorrect (AOFS). They seem to be copy and paste errors (e.g. Fighter has the texts of Captain skillsets) and some are not up to date with the latest campaign rules (v2.5 as far as I know; e.g. Support).

**Comment by AdamLay** [comment]
This has been merged and deployed now - thank you!
