### ISSUE TITLE
AF: HDF PDF vs. WC display issues

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#38]
1. Bulleted lists don't display well in the PDF version.
![image](https://user-images.githubusercontent.com/8975633/134915954-4ddeee48-494e-4a31-8190-ec1d15ba963a.png)

~~2. Special rules are not alphabetized as expected in the PDF version.~~
![image](https://user-images.githubusercontent.com/8975633/134916412-54d1a78f-b7b9-479e-a539-2a62044afd71.png)

~~3. Units with no upgrades, like Conscripts or Sniper Squad, have a lot of wasted whitespace in mobile view in PDF version.~~
![image](https://user-images.githubusercontent.com/8975633/134916828-6670f5dc-46df-45ee-a7a0-d6e8d1fb40eb.png)

4. Item name for Squad Weapon Detachment does not display consistently between versions.
![image](https://user-images.githubusercontent.com/8975633/134917288-a5ae5612-5ead-4c2d-935d-f61979f0b8a9.png)

~~5. Items with rules + weapons not displaying consistently.~~
![image](https://user-images.githubusercontent.com/8975633/134920534-9271dee2-c434-4104-b55e-e91de5434f2c.png)

~~6. Upgrade list B2 for Light APC parses differently between the versions.~~
![image](https://user-images.githubusercontent.com/8975633/134920865-27d2bea2-60c9-48ef-a6d2-147e38794fa3.png)

**Comment by AdamLay** [comment]
1. Not sure how we will handle this yet - need to check with @schnick3rs what the plan is for bullet lists?
4. Again, not sure how we are handling squad attachments

Everything else is resolved. 3. is expected behaviour if you flick/swipe the sheet up

**Comment by schnick3rs** [comment]
@AdamLay regarding (1)

Currently, I save special rules as markdown, thus a text with bullet list would be saved as

```
Some fancy text describing the stuff, also you have some options:

- **Options a:** pew pew
- **Option B:** stab stab
``

I use `"marked": "^2.1.3",` for markdown-2-html

**Comment by schnick3rs** [comment]
@AdamLay regarding (1)

Currently, the AF /data produces
```
            {
              "id": "Tp0obkY",
              "type": "ArmyBookUpgradeOption",
              "cost": 40,
              "label": "Squad Weapon Attachment (add one Weapons Team model with Heavy Machinegun)",
              "gains": [
                {
                  "id": "Tp0obkY",
                  "label": "Squad Weapon Attachment (add one Weapons Team model with Heavy Machinegun) +40pts",
                  "name": "Squad Weapon Attachment",
                  "specialRules": [
                    {
                      "key": "add one weapons team model with heavy machinegun",
                      "name": "add one Weapons Team model with Heavy Machinegun",
                      "rating": ""
                    }
                  ],
                  "cost": 40,
                  "type": "ArmyBookItem"
                }
              ]
            }
            ```
            
For unit attachments I currently use (propose) this format:
```
{
  type = 'ArmyBookUnitAttachment';

  name = ''Squad Weapon Attachment";
  unitUid: "***"
  unitString: "Weapons Team model with Heavy Machinegun"
  size: 1,
}
```
