### ISSUE TITLE
WA - Home screen

### ISSUE THREAD

**Issue by BaptisteD** [AdamLay/opr-army-forge#389]
1. Add breaking point for smaller screen width allowing the cards to be one on top of each other. 

<img src="https://user-images.githubusercontent.com/2566847/211832959-0aee89c6-e604-4f6f-acd6-affd8c9dbaec.jpeg" width="300" />

2. We could probably remove the "Section title" for this page. 

3. The <title> of the page is 
> Select your game system | OPR WebApp

it could probably be something like
> OPR Browse and create army books

**Comment by AdamLay** [comment]
good spot on the title! thank you - the section grouping is removed, and card style will change slightly. Also will fix mobile!

**Comment by AdamLay** [comment]
Done! :)
