### ISSUE TITLE
WA - Special Rules Glossary - Army books link

### ISSUE THREAD

**Issue by BaptisteD** [AdamLay/opr-army-forge#394]
For the button linking toward the army books using this specific rule, I would use the same icon as in the list showing the number of books. 
<img width="400" alt="Capture d’écran 2023-01-11 à 16 39 00" src="https://user-images.githubusercontent.com/2566847/211849353-72d2a4d5-5f1b-4921-b33a-0c05fc6f9831.png">

<img width="400" alt="Capture d’écran 2023-01-11 à 16 39 06" src="https://user-images.githubusercontent.com/2566847/211849584-34536ca2-4681-4968-a7a5-cb5a4f339578.png">

**Comment by AdamLay** [comment]
Done thanks :)
