### ISSUE TITLE
AF - Official and Fan books Tabs 

### ISSUE THREAD

**Issue by BaptisteD** [AdamLay/opr-army-forge#396]
<img width="400" alt="Capture d’écran 2023-01-11 à 16 54 04" src="https://user-images.githubusercontent.com/2566847/211853813-40c0f98d-c4c0-453e-b797-bb0bf570f57a.png">

1. There is a typo in the tabs: Official books

2. Make the text in font-weight: 600  like inside the list building. 
<img width="300" alt="Capture d’écran 2023-01-11 à 16 56 03" src="https://user-images.githubusercontent.com/2566847/211853747-fa6e08bb-f9f4-4c4e-9fb3-61ee7085ffbf.png">

**Comment by AdamLay** [comment]
Done - thanks! :)
