### ISSUE TITLE
AF: "Upgrade all CCWs" not counting properly for HDF Cavalry

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#40]
![image](https://user-images.githubusercontent.com/8975633/134922576-e2d669dc-1519-4ca4-ac6d-17eeeece7033.png)

**Comment by AdamLay** [comment]
I'm leaving this one open because whilst it's fixed, there are likely related issues due to upgrades being applied in a certain order!

**Comment by AdamLay** [comment]
Changed my mind - upgrade precedence is a separate issue!
