### ISSUE TITLE
AF: Weapon counts not displaying in "Upgrade any model with" scenario.

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#48]
1. Go to AOF `_Dwarves v2.9` book served by WC.
2. Add unit of Miners.
3. Add any number of Shrapnel Bombs upgrades. Count never increases in top profile.
![image](https://user-images.githubusercontent.com/8975633/134965993-3e753b9f-a2d1-46ef-bc60-7e636e08d31a.png)

**Comment by AdamLay** [comment]
This was also fixed with the same weapon count fix!
