### ISSUE TITLE
AF: Quality and Defense values don't end with a "+" suffix coming from WC.

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#50]
Look at any of the books served by WC and the Qua and Def values are just a number, without the "+" suffix.

![image](https://user-images.githubusercontent.com/8975633/134968312-5e700e6e-3837-46ce-8ea0-d66555156213.png)

![image](https://user-images.githubusercontent.com/8975633/134968367-1bdee033-cf89-437c-a318-0bf1d9e3fa26.png)

**Comment by schnick3rs** [comment]
WC Note: where possible, I try to save the/a numeric value and derive the readable string from that. Same for e.g. the Spell Threshold.

**Comment by AdamLay** [comment]
I have closed this - I've not actually seen any that aren't a number? AF used to store the string "3+" but since the conversion I am parsing the int value.
