### ISSUE TITLE
Design review - Game system selection screen

### ISSUE THREAD

**Issue by BaptisteD** [AdamLay/opr-army-forge#55]
- The page background should be white all along. Today there is a black line on the bottom. 
- Spacing between each game system should be consistent, vertically and horizontally 

![Screenshot_20211001-131524](https://user-images.githubusercontent.com/2566847/135627671-eaf4ca89-00b4-4f55-b43b-5758811cf6d4.jpg)

**Comment by AdamLay** [comment]
Hmm I cannot see a line at the bottom? there is nothing at the bottom of the page so might be your browser? I will close for now since the spacing is fixed, thanks
