### ISSUE TITLE
Incorrect parsing of Mounts with weapons or multiple special rules

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#6]
Parsing on Mounts doesn't account for weapon profiles or having multiple special rules. You can see this on the AOF Dwarves > Dwarf Lord character. The Ancestral Stone mount with a single special rule of "Tough(+3)" looks fine. The rest do not because they have multiple weapons/rules.

**Comment by AdamLay** [comment]
have added an exception for the format "Mount - Weapon(A2), Rules +20pts" - needs more testing I think, I have tested with the mounts only in Dwarves. Won't mark this closed until some other army files have been tested.

**Comment by Darguth** [comment]
@AdamLay Another variant of "mounts" can be found with various bike upgrades for hero units in GDF. For example if you look at the Combat Bike upgrade in GDF Dwarf Guilds upgrade list B1 it comes with a Twin Assault Rifle weapon profile.

Challenge here is that it's not clearly separated by a "Mount on:" upgrade title to know that it's a mount. It also exists in an upgrade table with non-mount options like Jetpack and Destroyer Armor.

**Comment by AdamLay** [comment]
GFF Format mounts are done now too - Combat Bike (Fast, Impact(1), Swift, Twin Assault Rifle (24”,A2)) +30pts

I'll retest with any I can find!
