### ISSUE TITLE
Underline & tooltip for special rules

### ISSUE THREAD

**Issue by BaptisteD** [AdamLay/opr-army-forge#72]
Special rules present in upgrade options should have the same behavior as the other special rules : underline and tooltip on hover/tap

<img width="410" alt="Capture d’écran 2021-10-09 à 22 14 22" src="https://user-images.githubusercontent.com/2566847/136672729-22034230-c0fc-4c2b-8a8e-9e8f42749123.png">

**Comment by BaptisteD** [comment]
The look of the underline isn't the same everywhere in the app. 

![Frame 5](https://user-images.githubusercontent.com/2566847/138131819-89a8e300-6584-4f84-80e9-28927cf14af4.png)

**Comment by AdamLay** [comment]
This is controlled by the font-size/browser and cannot be changed without a custom behaviour - closing for now
