### ISSUE TITLE
Double-selection of Pistol vs. 2x Pistols option for Dwarf Heroes

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#8]
In the AOF Dwarves v2.11 army book's Upgrade List B there is an option for a Pistol or 2x Pistols upgrades. In Army Forge there's several problems with this:
1. When I select either option, both radio buttons highlight as if selected. However, only the one I actually clicked on will update the weapon profile for the unit at the top of the pane or the unit cost in the center pane.
2. I cannot deselect the "2x Pistols" option once selected (though I can if just the "Pistol" option was).
3. The "2x Pistols" option parses to just "Pistols" and then if selected displays as "1x Pistols" in the unit's weapon profile.

![image](https://user-images.githubusercontent.com/8975633/134236839-37cdb3ec-06e2-4bb8-88b4-e97bd6379f61.png)

**Comment by AdamLay** [comment]
This was resolved with the "2x Hand Weapons" fix
