### ISSUE TITLE
Data Persistence - Export

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#82]
**User Story**
As an AF list builder
I want to be able to export the raw data of saved lists
So that I can transfer them between devices or share with other users.

**Acceptance Criteria**
1. Action is presented to the user to export a saved list.
2. Export action allows the user to save the army's .json file to a selected destination on their device.
3. Exported .json needs to include all relevant information needed to import the file back into the app later.

**Comment by AdamLay** [comment]
Points 1 and 3 are done - point 2 would be handled by the browser. I'm tempted to close this for now and add point 2 as an enhancement? @Darguth 

Also would like to look into the "web sharing API" or whatever it's called so that mobile devices pop up the native "share" dialog.
