### ISSUE TITLE
Unit Cards - Move Value

### ISSUE THREAD

**Issue by Darguth** [AdamLay/opr-army-forge#85]
**User Story**
As an AF list builder
I want to the unit cards to clearly display a base unit speed value
So that I can quickly reference their speed without parsing through other special rules.

**Acceptance Criteria**
1. Speed "container icon" similar to Quality and Defense exists to show the value.
2. Values are shown with an inches `"` suffix.
3. Special rules like Fast, Slow, Very Fast and Swift all still display in the rules section.
4. Values to be shown are:
- Default = `6"`
- Fast = `9"`
- Slow = `4"`
- Very Fast = `12"`
- Swift + Slow = `6"`

**Comment by BaptisteD** [comment]
Not sure for this one as the vast majority of the units in OPR system have the same move value. 
I would try to avoid overloading the "stats" part of the cards as it's reflecting the OPR simplicity.

**Comment by AdamLay** [comment]
Not sure about this - one the one hand I agree about overcomplicating the unit card, on the other hand my wife keeps asking "how far can this one move?" !

**Comment by BaptisteD** [comment]
Does her units have different move value ? 
I mainly play Orks and they all have the same. So it'll be quite redondante. 
It's not as much of a unit value than a game rule. (IMO)

**Comment by AdamLay** [comment]
Agreed - let's close it.
No, she always play RL and they all move 4" lol!
